- name: Install nginx
  yum:
    name: nginx
    state: present

- name: Copy index
  copy:
    src: ../../nginx/index.html
    dest: /usr/share/nginx/html/index.html

- name: Copy config
  copy:
    src: ../../nginx/nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Start nginx
  service:
    name: nginx
    state: started
    enabled: yes
