name: Enterprise Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # üîê Security scanning
      - uses: gitleaks/gitleaks-action@v2

      - uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs

      # AWS auth
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # Terraform
      - uses: hashicorp/setup-terraform@v3

      - run: terraform -chdir=terraform init

      - run: |
          terraform -chdir=terraform apply -auto-approve \
            -var "ami_id=${{ secrets.AMI_ID }}" \
            -var "db_password=${{ secrets.DB_PASSWORD }}"

      # Install Ansible + AWS plugin
      - run: |
          sudo apt install -y ansible
          pip install boto boto3 botocore

      # Deploy via SSM
      - run: |
          ANSIBLE_HOST_KEY_CHECKING=False \
          ansible-playbook -i ansible/inventory.ini ansible/deploy.yml
